name: Scheduled Tests
on:
  push:
    branches:
      - feat/test-cases
  schedule:
    - cron: '*/1 * * * *' # Runs every 5 minutes

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Run tests
        run: |
          echo "Running tests..."
          # Insert your test command here
          # For example:
          # npm install
          # npm test
