name: Create Next App with Gluestack UI (isProduction)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: packages/create-next-app-with-gluestack-ui
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies (prevent updates to lock file)
        working-directory: ${{ env.working-directory }}
        run: yarn
      - name: Testing Production
        working-directory: ${{ env.working-directory }}
        run: yarn test:production
      - name: Notify Failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C05HGN9LFV0
          status: FAILED by @${{ github.actor}}, Notify <@U047HGWBG>
          color: danger
