name: Cron Job

on:
  push:
    branches:
      - feat/test-github-action

  schedule:
    - cron: '*/1 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Your Job Step
        run: |
          echo 1
